import {C,LEVELS,PLACES,NAMES,SKILLS} from './config.js';
import {ERRORS,gridWidth} from './math.js';
import {load,save,fresh,KEY,streak} from './storage.js';
import {mastery} from './learning.js';
import {start,nextTask,submitCalculation,finishCalculation,startFocus,prepareWork,selectField,enterDigit,chooseLevel} from './session.js';
import {cardCanvas,shareCard} from './share.js';
import {comparePhases} from './rewards.js';
const app=document.querySelector('#app'),notice=document.querySelector('#notice');let state,view='home',feedback='',feedbackBad=false,blocked=false,lastTick=performance.now(),lastSave=0;
const button=(text,action,cls='')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
function warn(text){notice.textContent=text;notice.hidden=false;}
try{state=load(localStorage);if(state.session?.active){prepareWork(state.session.active);state.session.active.interrupted=true;}}catch{blocked=true;app.innerHTML='<h1>Lernstand geschützt</h1><p>Die gespeicherten Daten können nicht gelesen werden. Sie wurden nicht überschrieben.</p><p>Bitte die Daten sichern und prüfen lassen.</p>';}
function persist(){try{save(state,localStorage);return true;}catch{blocked=true;warn('Speichern nicht möglich. Bitte Speicherplatz freigeben. Dein Training bleibt hier offen.');return false;}}
function tick(){const now=performance.now(),delta=Math.max(0,now-lastTick);lastTick=now;const s=state?.session;if(!blocked&&!document.hidden&&view==='training'&&['a','b'].includes(s?.stage)&&s.active&&!s.active.resolved){s.elapsed+=delta;s.active.totalMs+=delta;s.active.columnMs+=delta;const w=s.active;if(!w.firstSubmission)w.columnTimes[w.selected.place]=(w.columnTimes[w.selected.place]||0)+delta;if(now-lastSave>2000){persist();lastSave=now;}}}
function home(){const s=state.session,resumable=s&&s.stage!=='done';return `<p class="eyebrow">DEIN RECHENTRAINING</p><h1>Eine Stelle nach der anderen.</h1><div class="panel"><p><strong>3 Minuten üben.</strong><br>Dann 2 Minuten gezielt weiter.</p><p class="muted">Du rechnest in Ruhe zu Ende.</p>${resumable?button('Training fortsetzen','resume','primary'):button('Training starten','start','primary')}</div><div class="row"><p><strong>Stufe ${state.selectedLevel}</strong><br>${LEVELS[state.selectedLevel].label}</p>${button('Wählen','levels')}</div><div class="stats"><div class="stat"><strong>${state.successNumber}</strong>Erfolge</div><div class="stat"><strong>${streak(state)}</strong>Tage in Folge</div></div><details><summary>So geht’s</summary><p>Beginne rechts bei den Einern. Tippe eine Ergebnisziffer ein.</p><p>Brauchst du eine Hilfs-1? Tippe ihre Stelle in der kleinen Zeile an und trage sie ein. Rechne in Ruhe weiter. Am Ende: „Ergebnis prüfen“.</p><p>Bei der letzten Stelle wird eine neue führende 1 direkt ins Ergebnis geschrieben.</p><p>Bei Minus: Rechne die Hilfs-1 zur unteren Ziffer dazu.</p></details>${button('Lernfortschritt','progress','secondary')}<p class="eyebrow">Ohne Konto. Dein Lernstand bleibt auf diesem Gerät.</p><p class="eyebrow">Version 1.1.3 · Alle zehn Stufen verfügbar</p>`;}
function levels(){return `${button('← Zurück','home','plain')}<h1>Deine Stufen</h1><div class="levels">${LEVELS.slice(1).map((l,i)=>{const n=i+1;return `<button data-level="${n}" aria-pressed="${state.selectedLevel===n}"><span class="badge">${n}</span><span>${l.label}</span></button>`;}).join('')}</div><p class="muted">Alle zehn Stufen sind verfügbar. Wähle, was du üben möchtest.</p>`;}
function grid(w){const t=w.task,n=gridWidth(t),places=Array.from({length:n},(_,i)=>n-1-i);let html=`<div class="grid" style="--columns:${n}" role="group" aria-label="Stellenraster">`;
 for(const row of ['label','top','bottom','helper','result']){html+=`<div class="cell operator ${row}">${row==='bottom'?(t.operation==='+'?'+':'−'):''}</div>`;
 for(const p of places){const selected=w.selected.kind===row&&w.selected.place===p,checked=w.validation?.fields[row]?.[p]===true,incorrect=w.validation?.fields[row]?.[p]===false,active=p===w.p;let content;
 if(row==='label')content=PLACES[p];else if(row==='top'||row==='bottom'){const num=row==='top'?t.a:t.b;content=num>=10**p?Math.floor(num/10**p)%10:'';}
 else if(row==='helper'){content=`<button data-cell="helper:${p}" aria-label="Hilfszahl ${NAMES[p]}${w.helpers[p]!==undefined&&w.helpers[p]!==null?', '+w.helpers[p]:', leer'}" aria-pressed="${selected}" ${w.resolved?'disabled':''} aria-invalid="${incorrect}">${w.helpers[p]??'·'}</button>`;}
 else content=`<button data-cell="result:${p}" aria-label="Ergebnis ${NAMES[p]}${w.results[p]!==undefined&&w.results[p]!==null?', '+w.results[p]:', leer'}" aria-pressed="${selected}" ${w.resolved?'disabled':''} aria-invalid="${incorrect}">${w.results[p]??'·'}</button>`;
 html+=`<div class="cell ${row} ${checked?'checked':''} ${incorrect?'incorrect':''} ${active?'active-column':''}" data-row="${row}" data-place="${p}">${content}</div>`;
 }}return html+'</div>';}
function calculationFeedback(w){
 const r=w.validation;if(!r)return 'Rechne in Ruhe. Prüfe am Ende.';
 if(r.ok)return '✓ Ergebnis und Rechenweg stimmen.';
 const error=r.errors[0];
 if(r.numericCorrect&&error.kind==='helper')return `✕ Das Ergebnis stimmt. Prüfe die Hilfszahl: ${NAMES[error.place]}.`;
 return error.kind==='helper'?`✕ Prüfe die Hilfszahl: ${NAMES[error.place]}.`:`✕ Prüfe die Ergebnisstelle: ${NAMES[error.place]}.`;
}
function training(){const w=state.session.active;return `<div class="training"><div class="row"><p class="eyebrow">${state.session.stage==='a'?'3 Minuten üben':'2 Minuten gezielt üben'}</p>${button('Pause','pause','plain')}</div><h1>${w.resolved?'Rechnung geschafft':NAMES[w.selected.place]}</h1>${grid(w)}<p class="legend">Zahlen · kleine Hilfszeile · Ergebnis</p><div class="feedback ${w.validation?(w.validation.ok?'good':'bad'):''}" role="status" aria-live="polite">${calculationFeedback(w)}</div>${w.resolved?button('Weiter','finish','primary'):`<p class="eyebrow">Eingabe: ${w.selected.kind==='helper'?'Hilfszahl':'Ergebnis'} · ${NAMES[w.selected.place]}</p><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-digit="${n}">${n}</button>`).join('')}${button('Löschen','erase','delete')}<button data-digit="0">0</button>${button('Ergebnis','result','delete')}</div>${button('Ergebnis prüfen','check','primary')}`}</div>`;}
function report(){const s=state.session,phase=s.stage==='between'?'a':'b',r=s.reports[phase],card=state.cards.find(c=>c.id===r.id),comparison=phase==='b'?comparePhases(s.rows.a,s.rows.b):null;return `<p class="eyebrow">${phase==='a'?'ERSTE RUNDE GESCHAFFT':'DIESE RUNDE IST GESCHAFFT'}</p><h1>${card?`Erfolg Nr. ${card.number}`:'Stark drangeblieben!'}</h1><div class="panel"><h2>${r.total} Rechnungen geübt.</h2><p>${r.correct} davon beim ersten Prüfen richtig.</p><p>${r.correctColumns} von ${r.columns} Ergebnisstellen beim ersten Versuch richtig.</p>${card?`<p><strong>${Math.round(r.score*100)} % Trainingswertung</strong><br>${card.streak} ${card.streak===1?'Tag':'Tage'} in Folge erfolgreich gelernt.</p>`:'<p>Jede geübte Stelle zählt.</p>'}${comparison?`<p>Bei vergleichbaren Aufgaben: ${Math.round(comparison.before*100)} % in Runde 1, ${Math.round(comparison.after*100)} % in Runde 2.</p>`:''}</div>${card?button('Erfolgskarte ansehen','card','secondary'):''}${phase==='a'?`<p>Jetzt übst du 2 Minuten gezielt weiter.</p>${button('2-Minuten-Training starten','focus','primary')}`:`<p>Gut geübt! Wähle jetzt eine andere Stufe, die du für deine Klassenarbeit können solltest.</p>${button('Andere Stufe üben','levels','primary')}${button('Zur Startseite','home','secondary')}`}`;}
function progress(){const counts={};for(const e of state.errors.slice(-60))counts[e.type]=(counts[e.type]||0)+1;return `${button('← Zurück','home','plain')}<h1>Lernfortschritt</h1><div class="stats">${[[state.learningDays.length,'Lerntage'],[state.successNumber,'Erfolge'],[streak(state),'Tage in Folge'],[state.longestStreak,'Längste Folge']].map(([n,label])=>`<div class="stat"><strong>${n}</strong>${label}</div>`).join('')}</div><p>Alle zehn Stufen sind verfügbar.</p><p>Geübte Stufen: ${Object.keys(state.levelProgress).filter(n=>state.levelProgress[n].tasks>0).join(', ')||'Noch keine'}</p><h2>Das wird geübt</h2>${Object.entries(SKILLS).map(([key,label])=>`<div class="skill"><strong>${label}</strong><span>${mastery(state.skills[key])}</span></div>`).join('')}<h2>Wiederholt aufgefallen</h2>${Object.entries(counts).filter(([,n])=>n>=3).map(([type])=>`<p>${ERRORS[type]}</p>`).join('')||'<p>Noch kein wiederkehrendes Muster.</p>'}<details><summary>Wie werden Erfolge gezählt?</summary><p>Mindestens 90 % Trainingswertung, mindestens 3 Rechnungen und 8 Stellen in der ersten Runde; 2 Rechnungen und 6 Stellen in der zweiten. Korrigierte Schritte bleiben als Lernhinweis erhalten.</p><p>Die Wertung berücksichtigt ganze Rechnungen, Ergebnisstellen und nötige Hilfszahlen. Sie ist unabhängig vom Können einer einzelnen Fertigkeit.</p></details><details><summary>Erfolgskarten</summary>${state.cards.slice(-20).reverse().map(c=>button(`Erfolg Nr. ${c.number} · ${c.date.split('-').reverse().join('.')}`,`card:${c.number}`,'secondary')).join('')||'<p>Noch keine Erfolgskarte.</p>'}</details><details><summary>Einstellungen</summary>${button('Lerndaten sichern','export','secondary')}${button('Lerndaten zurücksetzen','reset','secondary danger')}</details>`;}
let selectedCard=null;
function render(){if(blocked)return;app.innerHTML=view==='home'?home():view==='levels'?levels():view==='training'?training():view==='report'?report():view==='progress'?progress():view==='paused'?`<h1>Pause</h1><p>Deine Rechnung bleibt erhalten.</p>${button('Weiterrechnen','resume','primary')}${button('Zur Startseite','home','secondary')}`:view==='reset'?`<h1>Lerndaten zurücksetzen?</h1><p>Alle Erfolge, Rechnungen und Lernbeobachtungen auf diesem Gerät werden gelöscht. Alle zehn Stufen bleiben verfügbar.</p>${button('Abbrechen','progress','primary')}${button('Ja, alle Lerndaten löschen','confirm-reset','secondary danger')}`:view==='card'?`${button('← Zurück','progress','plain')}<h1>Deine Erfolgskarte</h1><img id="card-image" class="card-image" alt="Erfolg Nr. ${selectedCard.number}, ${Math.round(selectedCard.score*100)} Prozent Trainingswertung"><p>${button('Karte teilen oder speichern','share','primary')}</p>`:'';if(view==='training')document.querySelector('[data-cell][aria-pressed="true"]')?.focus?.({preventScroll:true});if(view==='card')document.querySelector('#card-image').src=cardCanvas(selectedCard).toDataURL('image/png');}
function resume(){const s=state.session;if(['a','b'].includes(s?.stage)){if(!s.active)nextTask(state);view='training';}else view=s?'report':'home';lastTick=performance.now();}
function firstAction(){const w=state.session?.active;if(w&&w.firstMs===null)w.firstMs=w.totalMs;}
function action(a){tick();feedback='';feedbackBad=false;
 if(['home','levels','progress','reset'].includes(a))view=a;
 else if(a==='start'){if(start(state,state.selectedLevel))resume();}
 else if(a==='resume')resume();
 else if(a==='pause')view='paused';
 else if(a==='focus'){if(startFocus(state))resume();}
 else if(a==='confirm-reset'){state=fresh();view='home';}
 else if(a==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='AddiSub-Lernstand.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 else if(a==='card'||a.startsWith('card:')){selectedCard=a.includes(':')?state.cards.find(c=>c.number===+a.split(':')[1]):state.cards.find(c=>c.id===state.session.reports[state.session.stage==='between'?'a':'b'].id);view='card';}
 else if(a==='share'){shareCard(selectedCard).catch(e=>{if(e.name!=='AbortError')warn('Die Karte konnte nicht geteilt werden. Bitte noch einmal versuchen.');});}
 else {const w=state.session?.active;if(!w)return;firstAction();
  if(a==='erase')enterDigit(w,null);
  if(a==='result')selectField(w,'result',w.selected.place);
  if(a==='check')submitCalculation(w);
  if(a==='finish'&&finishCalculation(state)){if(state.session.stage==='between'||state.session.stage==='done')view='report';else nextTask(state);}
 }persist();render();}
app.addEventListener('click',e=>{if(blocked)return;const b=e.target.closest('button');if(!b||b.disabled)return;tick();if(b.dataset.action)return action(b.dataset.action);if(b.dataset.level){chooseLevel(state,+b.dataset.level);view='home';persist();render();return;}const w=state.session?.active;if(!w||view!=='training')return;firstAction();if(b.dataset.cell){const [kind,p]=b.dataset.cell.split(':');selectField(w,kind,+p);}if(b.dataset.digit!==undefined)enterDigit(w,+b.dataset.digit);persist();render();});
document.addEventListener('keydown',e=>{if(view!=='training'||blocked||e.ctrlKey||e.metaKey||e.altKey)return;if(e.target.closest('button')&&['Enter',' '].includes(e.key))return;if(/^\d$/.test(e.key)){document.querySelector(`[data-digit="${e.key}"]`)?.click();e.preventDefault();}else if(e.key==='Backspace'){action('erase');e.preventDefault();}else if(e.key==='Enter'){action(state.session.active.resolved?'finish':'check');e.preventDefault();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){tick();if(state?.session?.active)state.session.active.interrupted=true;if(!blocked)persist();}lastTick=performance.now();});window.addEventListener('pagehide',()=>{tick();if(!blocked)persist();});window.addEventListener('storage',e=>{if(e.key===KEY){blocked=true;warn('Der Lernstand wurde in einem anderen Fenster geändert. Bitte diese Seite neu laden.');}});
setInterval(tick,500);render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').then(()=>{}).catch(()=>warn('Offline-Speicherung ist gerade nicht verfügbar. Online kannst du weiter üben.'));
