import {C} from './config.js';
import {validateTask} from './math.js';
export const KEY='addisub-learning-v1';
export const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const ordinal=s=>{const [y,m,d]=s.split('-').map(Number);return Date.UTC(y,m-1,d)/86400000;};
export const fresh=()=>({schemaVersion:C.schemaVersion,revision:0,skills:{},facts:{},history:[],errors:[],daily:{},session:null,unlockedLevels:[1],levelProgress:{},successNumber:0,currentStreak:0,longestStreak:0,lastQualifyingSuccessDate:null,learningDays:[],awarded:{},cards:[],selectedLevel:1});
export function validate(s){if(!s||s.schemaVersion!==C.schemaVersion)throw Error('Unbekannte Datenversion');for(const k of ['skills','facts','daily','levelProgress','awarded'])if(!s[k]||typeof s[k]!=='object'||Array.isArray(s[k]))throw Error('Beschädigte Daten');for(const k of ['history','errors','unlockedLevels','learningDays','cards'])if(!Array.isArray(s[k]))throw Error('Beschädigte Listen');for(const k of ['revision','successNumber','currentStreak','longestStreak'])if(!Number.isSafeInteger(s[k])||s[k]<0)throw Error('Beschädigte Zähler');if(!s.unlockedLevels.includes(1)||s.unlockedLevels.some(n=>!Number.isInteger(n)||n<1||n>10))throw Error('Beschädigte Stufen');if(s.session&&(!['a','b','between','done'].includes(s.session.stage)||!Number.isFinite(s.session.elapsed)||s.session.elapsed<0||!s.session.rows||!Array.isArray(s.session.rows.a)||!Array.isArray(s.session.rows.b)))throw Error('Beschädigtes Training');return s;}
export function load(storage){const raw=storage.getItem(KEY);if(!raw)return fresh();const s=validate(JSON.parse(raw));
 for(const skill of [...Object.values(s.skills),...Object.values(s.facts)])if(!Number.isInteger(skill.n)||!Number.isInteger(skill.correct)||skill.n<0||skill.correct>skill.n||!Array.isArray(skill.recent)||skill.recent.some(r=>typeof r.ok!=='boolean'||r.ms!==null&&(!Number.isFinite(r.ms)||r.ms<0)))throw Error('Beschädigte Lernbeobachtung');
 if(!s.unlockedLevels.includes(s.selectedLevel))throw Error('Ungültige Auswahl');
 const w=s.session?.active;if(w){if(!validateTask(w.task)||!Number.isInteger(w.p)||w.p<0||w.p>=w.task.columns.length||!w.results||!w.helpers||!Array.isArray(w.errors)||!Array.isArray(w.stepErrors)||!Array.isArray(w.evidence)||!w.selected||!['helper','result'].includes(w.selected.kind))throw Error('Beschädigte Rechnung');for(const map of [w.results,w.helpers])for(const [p,n] of Object.entries(map))if(!/^[0-6]$/.test(p)||n!==null&&(!Number.isInteger(n)||n<0||n>9))throw Error('Ungültige Ziffer');for(const key of ['totalMs','columnMs'])if(!Number.isFinite(w[key])||w[key]<0)throw Error('Ungültige Zeit');}
 return s;}
export function save(s,storage){s.revision++;storage.setItem(KEY,JSON.stringify(s));}
export function streak(s,today=dayKey()){return s.lastQualifyingSuccessDate&&ordinal(today)-ordinal(s.lastQualifyingSuccessDate)<=1?s.currentStreak:0;}
