import test from 'node:test';import assert from 'node:assert/strict';
import {model,checkCalculation,gridWidth} from '../math.js';import {fresh,load,save,KEY} from '../storage.js';import {C} from '../config.js';
import {start,nextTask,selectField,enterDigit,submitCalculation,finishCalculation,startFocus,chooseLevel} from '../session.js';import {summarize} from '../rewards.js';
const store=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
function setup(t){const s=fresh();start(s,t.level);nextTask(s);s.session.active.task=t;return s;}
function fill(w){for(const c of w.task.columns){selectField(w,'result',c.place);enterDigit(w,c.expected);if(c.helperRequired){selectField(w,'helper',c.helperPlace);enterDigit(w,1);}}}
for(const [a,b,op] of [[23,14,'+'],[987,248,'+'],[999,1,'+'],[99999,1,'+'],[999999,1,'+'],[731,265,'-'],[638427,259684,'-'],[5002,2786,'-'],[1000000,1,'-']])test(`complete submission ${a}${op}${b}; no entry-time validation`,()=>{const t=model(a,b,op),s=setup(t),w=s.session.active;fill(w);assert.equal(w.firstSubmission,null);assert.equal(w.validation,null);assert.equal(w.errors.length,0);assert.equal(w.submissions,0);assert.ok(submitCalculation(w).ok);assert.ok(finishCalculation(s));assert.equal(s.history[0].ok,true);assert.equal(s.history[0].firstSubmission.value,t.result);});
test('result-length independent capacity and focus for same operand widths',()=>{const a=setup(model(23,14)).session.active,b=setup(model(99,14)).session.active;assert.equal(gridWidth(a.task),gridWidth(b.task));for(const w of [a,b]){enterDigit(w,7);assert.equal(w.p,1);enterDigit(w,3);assert.equal(w.p,2);assert.equal(w.resolved,false);assert.equal(w.validation,null);}assert.ok(submitCalculation(a).ok);assert.equal(submitCalculation(b).ok,false);});
test('wrong result and helper never block movement or editing',()=>{const w=setup(model(731,265,'-')).session.active;enterDigit(w,9);assert.equal(w.p,1);enterDigit(w,2);selectField(w,'helper',0);enterDigit(w,8);assert.equal(w.validation,null);selectField(w,'result',0);enterDigit(w,null);assert.equal(w.results[0],null);fill(w);selectField(w,'helper',0);enterDigit(w,null);assert.ok(submitCalculation(w).ok);assert.equal(w.firstSubmission.errors.length,0);});
test('numeric result and full helper path are independent',()=>{const t=model(731,265,'-');let r=checkCalculation(t,{0:6,1:6,2:4},{1:1});assert.ok(r.numericCorrect);assert.equal(r.pathCorrect,false);assert.ok(r.errors.some(e=>e.type==='SUBTRACTION_HELPER_MISSING'&&e.place===2));r=checkCalculation(t,{0:6,1:6,2:4},{1:1,0:1});assert.ok(r.errors.some(e=>e.type==='SUBTRACTION_HELPER_WRONG_COLUMN'));r=checkCalculation(t,{0:6,1:6,2:4},{1:1,2:1,0:1});assert.ok(r.errors.some(e=>e.type==='UNNECESSARY_CARRY'));});
test('earlier correct fields stay intact, only submitted mistakes highlighted',()=>{const w=setup(model(987,248)).session.active;fill(w);selectField(w,'result',2);enterDigit(w,4);const r=submitCalculation(w);assert.equal(r.fields.result[0],true);assert.equal(r.fields.result[1],true);assert.equal(r.fields.result[2],false);assert.deepEqual(w.results,{0:5,1:3,2:4,3:1});selectField(w,'result',2);enterDigit(w,2);assert.ok(submitCalculation(w).ok);assert.equal(w.firstSubmission.results[2],4);assert.equal(w.corrections,1);});
test('reload after failed submit preserves immutable first attempt and corrections',()=>{let s=setup(model(731,265,'-',4,4));let w=s.session.active;fill(w);selectField(w,'helper',2);enterDigit(w,null);submitCalculation(w);const storage=store();save(s,storage);s=load(storage);w=s.session.active;selectField(w,'helper',2);enterDigit(w,1);assert.ok(submitCalculation(w).ok);finishCalculation(s);const r=s.history[0];assert.equal(r.firstSubmissionCorrect,false);assert.equal(r.finalCorrect,true);assert.equal(r.corrections,1);assert.equal(r.firstSubmission.helpers[2],null);assert.equal(r.finalSubmission.helpers[2],1);assert.equal(s.skills.helper.correct,1);assert.equal(s.skills.helper.n,2);assert.equal(s.errors[0].type,'SUBTRACTION_HELPER_MISSING');assert.ok(summarize([r]).score<.9);});
test('timer waits through failed submit, correction and completed exercise in both phases',()=>{const s=setup(model(731,265,'-',4,4));for(const phase of ['a','b']){const w=s.session.active;s.session.elapsed=phase==='a'?C.generalMs:C.focusMs;fill(w);selectField(w,'result',0);enterDigit(w,0);assert.equal(submitCalculation(w).ok,false);assert.equal(finishCalculation(s),false);assert.equal(s.session.stage,phase);selectField(w,'result',0);enterDigit(w,6);assert.ok(submitCalculation(w).ok);assert.ok(finishCalculation(s));if(phase==='a'){assert.equal(s.session.stage,'between');assert.deepEqual(s.session.focus,[4]);startFocus(s);nextTask(s);s.session.active.task=model(731,265,'-',4,4);}}assert.equal(s.session.stage,'done');assert.equal(startFocus(s),false);});
test('all levels available on fresh state, legacy load, reset and subsequent reload',()=>{const storage=store(),s=fresh();assert.equal(s.unlockedLevels.length,10);s.unlockedLevels=[1];s.successNumber=7;s.currentStreak=3;s.history=[{key:'saved'}];save(s,storage);const migrated=load(storage);assert.equal(migrated.unlockedLevels.length,10);assert.equal(migrated.successNumber,7);assert.equal(migrated.currentStreak,3);assert.deepEqual(migrated.history,s.history);save(migrated,storage);assert.equal(load(storage).unlockedLevels.length,10);save(fresh(),storage);assert.equal(load(storage).unlockedLevels.length,10);});
test('legacy active work preserves entered digits without claiming assisted work independent',()=>{const s=setup(model(987,248));const w=s.session.active;delete w.inputVersion;delete w.firstSubmission;w.results={0:5};w.helpers={1:1};w.evidence=[{errors:[],ms:1000,resultOK:true,helperOK:true}];const storage=store();save(s,storage);const migrated=load(storage),mw=migrated.session.active;assert.equal(mw.results[0],5);assert.equal(mw.helpers[1],1);assert.equal(mw.legacyAssisted,true);fill(mw);submitCalculation(mw);finishCalculation(migrated);assert.equal(migrated.history[0].independent,false);assert.equal(migrated.history[0].ok,false);});
test('empty, incomplete and superfluous result places are diagnosed only on submission',()=>{const t=model(23,14);assert.equal(checkCalculation(t,{},{}).ok,false);assert.equal(checkCalculation(t,{0:7},{}).ok,false);const r=checkCalculation(t,{0:7,1:3,2:0},{});assert.equal(r.numericCorrect,true);assert.equal(r.pathCorrect,false);assert.equal(r.errors[0].type,'FINAL_COLUMN_ERROR');});
test('selecting another level pauses current work without blocking advanced training',()=>{let s=setup(model(23,14));enterDigit(s.session.active,7);chooseLevel(s,10);assert.equal(s.session,null);assert.ok(start(s,10));nextTask(s);const advanced=s.session.active.task;const storage=store();save(s,storage);s=load(storage);chooseLevel(s,1);assert.equal(s.session.active.results[0],7);assert.equal(s.session.active.p,1);assert.equal(s.selectedLevel,1);chooseLevel(s,10);assert.deepEqual(s.session.active.task,advanced);});
