import test from 'node:test';import assert from 'node:assert/strict';import {fresh,load,save,streak} from '../storage.js';import {C} from '../config.js';import {observe,mastery,chooseFamily,focusFrom} from '../learning.js';import {summarize,award,qualifies} from '../rewards.js';import {start,nextTask,submitCalculation,finishCalculation,startFocus,enterDigit,selectField} from '../session.js';import {model} from '../math.js';
const row=(over={})=>({family:3,ok:true,columns:3,helpers:1,correctColumns:3,correctHelpers:1,resolved:true,errors:[],normalizedMs:4000,...over});
test('normalized score and meaningful-work floor',()=>{const r={...summarize([row(),row(),row()]),phase:'a'};assert.equal(r.score,1);assert.ok(qualifies(r));assert.ok(!qualifies({...summarize([row()]),phase:'a'}));assert.ok(!qualifies({...r,resolved:false}));assert.equal(summarize([row({ok:false,correctHelpers:0})]).score,.4);});
test('phase rewards idempotent after reload; local-day streak',()=>{let s=fresh();s.levelProgress[1]={successes:0};const r={...summarize([row(),row(),row()]),phase:'a',id:'x:a',level:1};award(s,r,'2026-09-20');s=JSON.parse(JSON.stringify(s));award(s,r,'2026-09-20');assert.equal(s.successNumber,1);award(s,{...r,id:'x:b',phase:'b'},'2026-09-20');assert.equal(s.successNumber,2);assert.equal(s.currentStreak,1);award(s,{...r,id:'y:a'},'2026-09-21');assert.equal(s.currentStreak,2);assert.equal(streak(s,'2026-09-23'),0);award(s,{...r,id:'z:a'},'2026-09-24');assert.equal(s.currentStreak,1);assert.equal(s.longestStreak,2);});
test('success and mastery independent; speed secondary; sufficient evidence',()=>{const s=fresh();observe(s.skills,'carry',true,1000);assert.equal(mastery(s.skills.carry),'Noch nicht ausreichend geübt.');for(let i=1;i<12;i++)observe(s.skills,'carry',true,25000);assert.equal(mastery(s.skills.carry),'Richtig, aber noch langsam');for(let i=0;i<36;i++)observe(s.skills,'carry',true,2000);assert.equal(mastery(s.skills.carry),'Automatisiert');});
test('target evidence, weighted practice, no fixation, spaced return',()=>{const s=fresh();assert.deepEqual(focusFrom([row({family:4,errors:['SUBTRACTION_HELPER_MISSING']}),row()]),[4]);s.history=[row({family:4}),row({family:4})];for(let i=0;i<100;i++)assert.notEqual(chooseFamily(s,8,[4]),4);s.history=[];const count={};for(let i=0;i<700;i++){const f=chooseFamily(s,8,[4],()=>i/700);count[f]=(count[f]||0)+1;}assert.ok(count[4]>count[3]);assert.equal(Object.keys(count).length,7);});
test('every level starts without learning evidence',()=>{for(let level=1;level<=10;level++){const s=fresh();s.unlockedLevels=[1];assert.ok(start(s,level));assert.equal(nextTask(s).task.level,level);}});
function solve(s){const w=s.session.active;for(const c of w.task.columns){w.results[c.place]=c.expected;if(c.helperRequired)w.helpers[c.helperPlace]=1;}assert.ok(submitCalculation(w).ok);return finishCalculation(s,'2026-09-20');}
test('3+2 session ends only after complete calculation, no third phase',()=>{const s=fresh();start(s,1,'session');nextTask(s);s.session.elapsed=C.generalMs;assert.equal(s.session.stage,'a');solve(s);assert.equal(s.session.stage,'between');assert.ok(startFocus(s));nextTask(s);s.session.elapsed=C.focusMs;solve(s);assert.equal(s.session.stage,'done');assert.equal(startFocus(s),false);assert.equal(nextTask(s),null);});
test('correction preserves earlier work and first-submission evidence',()=>{const s=fresh();start(s,1);const w=nextTask(s);w.task=model(731,265,'-');w.results={0:6,1:7,2:4};w.helpers={1:1,2:1};assert.equal(submitCalculation(w).ok,false);assert.equal(w.results[0],6);selectField(w,'result',1);enterDigit(w,6);assert.ok(submitCalculation(w).ok);assert.equal(w.firstSubmission.ok,false);assert.ok(finishCalculation(s));assert.equal(s.history[0].ok,false);assert.equal(s.history[0].finalCorrect,true);assert.ok(s.history[0].errors.includes('SUBTRACTION_HELPER_NOT_USED'));});
test('storage roundtrip and invalid schemas fail without silent reset',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const s=fresh();save(s,storage);assert.deepEqual(load(storage),s);s.schemaVersion=99;save(s,storage);assert.throws(()=>load(storage));});
